name: papers
description: Wallpapers app.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  infinite_scroll_pagination: ^3.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  retrofit: ^3.0.1+1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  pixel_perfect: ^1.1.1
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/google_fonts/Lato/
    - assets/google_fonts/Montserrat/
    - assets/google_fonts/Raleway/
  fonts:
    - family:  PapersIcons
      fonts:
        - asset: assets/fonts/PapersIcons.ttf